server:
  port: 8000
spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: solar-nexus-datasuite
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level [%thread] %logger{50} - %msg%n"
  level:
    root: info
    com.polyu.tapgen: debug
  config: classpath:logback-spring.xml
influx:
  url: http://127.0.0.1:8086
  token: rtaL4HSq9C6vvH439pmov9qF_ZJXXPMY7xvzZdcdgPE-BT2HmzNX_ct9zHw0JBOPLs47PA9rwe1uLXJMqPuaWQ==
  bucket: tapgen
  org: poylu
modbus:
  tcp:
    timeout: 3000
    retries: 2
    reconnect-interval: 5000
  groups:
    - name: "group-1"
      devices:
        - name: "flowmeter_1"
          type: 'k24'
          host: "192.168.50.101"
          port: 8899
          slave-id: 1
        - name: "pressure_1"
          type: 'bs600'
          host: "192.168.50.102"
          port: 8899
          slave-id: 1
        - name: "ACPower_1"
          type: 'acpower'
          host: "192.168.50.103"
          port: 8899
          slave-id: 1
        - name: "DCPower_1"
          type: 'sui-201'
          host: "192.168.50.104"
          port: 8899
          slave-id: 1